<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyVersion>1.0.2</AssemblyVersion>
        <FileVersion>1.0.2</FileVersion>
        <PackageVersion>1.0.2</PackageVersion>
        <PackageId>argentini.duid</PackageId>
        <Authors>Michael Argentini</Authors>
        <Company>Argentini Unlimited, Ltd.</Company>
        <PackageTags>DUID GUID KSUID</PackageTags>
        <Description>128 bit globally unique identifier with more entropy than GUID, is URL-friendly, JavaScript entity name-friendly, and is high performance.</Description>
        <Copyright>Copyright (c) 2025 Argentini Unlimited, Ltd.</Copyright>
        <PackageProjectUrl>https://github.com/argentini/Argentini.Duid</PackageProjectUrl>
        <RepositoryUrl>https://github.com/argentini/Argentini.Duid</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReleaseNotes>Updated the README</PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <PackageOutputPath>nupkg</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="nuget-icon.png" Pack="true" PackagePath="" CopyToOutputDirectory="Always" />
        <None Include="..\README.md" Pack="true" PackagePath="" CopyToOutputDirectory="Always" />
        <None Include="..\LICENSE.txt" Pack="true" PackagePath="" CopyToOutputDirectory="Always" />
    </ItemGroup>

</Project>
